package handlers

import (
	"crypto/rand"
	"encoding/base64"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"

	"github.com/84adam/Arkfile/utils"
)

// Cookie name constants.
// __Host- prefix requires Secure + Path=/ + no Domain attribute, giving the
// strongest same-site binding available in modern browsers.
const (
	CookieFullToken = "__Host-arkfile-token"
	CookieTempToken = "__Host-arkfile-temp"
	CookieRefresh   = "__Host-arkfile-refresh"
	CookieCSRF      = "__Host-arkfile-csrf"
)

// refreshCookieMaxAge is the Max-Age for the refresh-token cookie.
// 7 days gives ample time without indefinite sessions.
const refreshCookieMaxAge = 7 * 24 * 60 * 60 // seconds

// GenerateCSRFToken returns a 32-byte cryptographically random string encoded
// as URL-safe base64 (44 chars). This is the value placed in the non-HttpOnly
// __Host-arkfile-csrf cookie that JavaScript reads and sends back in the
// X-CSRF-Token request header.
func GenerateCSRFToken() (string, error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return base64.URLEncoding.EncodeToString(b), nil
}

// issueSessionCookies writes the three session cookies to the response.
// Called on every path that completes a login or token rotation.
// csrfToken must be generated by the caller via GenerateCSRFToken().
// All cookies use __Host- prefix: Secure, SameSite=Strict, Path=/, no Domain.
func issueSessionCookies(c echo.Context, fullToken, refreshToken, csrfToken string) {
	jwtLifetime := utils.GetJWTTokenLifetime()
	jwtMaxAge := int(jwtLifetime.Seconds())

	// Full JWT — HttpOnly, expires with the JWT itself.
	c.SetCookie(&http.Cookie{
		Name:     CookieFullToken,
		Value:    fullToken,
		Path:     "/",
		MaxAge:   jwtMaxAge,
		Secure:   true,
		HttpOnly: true,
		SameSite: http.SameSiteStrictMode,
	})

	// Refresh token — HttpOnly, longer-lived.
	c.SetCookie(&http.Cookie{
		Name:     CookieRefresh,
		Value:    refreshToken,
		Path:     "/",
		MaxAge:   refreshCookieMaxAge,
		Secure:   true,
		HttpOnly: true,
		SameSite: http.SameSiteStrictMode,
	})

	// CSRF token — NOT HttpOnly so JavaScript can read it.
	// Rotated on every token issuance so a stolen value goes stale quickly.
	c.SetCookie(&http.Cookie{
		Name:     CookieCSRF,
		Value:    csrfToken,
		Path:     "/",
		MaxAge:   jwtMaxAge,
		Secure:   true,
		HttpOnly: false,
		SameSite: http.SameSiteStrictMode,
	})
}

// issueTempCookie writes the temp-tier JWT cookie used during the TOTP-handoff
// window. The cookie expires with the temp token (20 minutes).
func issueTempCookie(c echo.Context, tempToken string) {
	c.SetCookie(&http.Cookie{
		Name:     CookieTempToken,
		Value:    tempToken,
		Path:     "/",
		MaxAge:   20 * 60, // 20-minute temp token lifetime
		Secure:   true,
		HttpOnly: true,
		SameSite: http.SameSiteStrictMode,
	})
}

// clearSessionCookies expires all four Arkfile session cookies.
// Called on logout.
func clearSessionCookies(c echo.Context) {
	epoch := time.Unix(0, 0)
	for _, name := range []string{CookieFullToken, CookieTempToken, CookieRefresh, CookieCSRF} {
		c.SetCookie(&http.Cookie{
			Name:     name,
			Value:    "",
			Path:     "/",
			Expires:  epoch,
			MaxAge:   -1,
			Secure:   true,
			HttpOnly: true,
			SameSite: http.SameSiteStrictMode,
		})
	}
}
