#!/bin/bash

# Source common variables and functions
source "$(dirname "$0")/../utils/common.sh" 2>/dev/null || source "$(dirname "$0")/../../utils/common.sh" 2>/dev/null || {
    # Fallback if common.sh cannot be found
    ARKFILE_DIR="/opt/arkfile"
    GREEN='\033[0;32m'
    RED='\033[0;31m'
    YELLOW='\033[1;33m'
    NC='\033[0m'
    print_status() {
        echo -e "${GREEN}[$1] $2${NC}"
    }
    print_error() {
        echo -e "${RED}[ERROR] $1${NC}"
    }
}

SECRETS_FILE="$ARKFILE_DIR/etc/secrets.env"

print_status "INFO" "Setting up Master Key in secrets.env..."

# Ensure secrets.env exists (should be created by dev-reset.sh or other setup scripts)
if [ ! -f "$SECRETS_FILE" ]; then
    print_status "INFO" "Creating secrets.env file..."
    mkdir -p "$(dirname "$SECRETS_FILE")"
    touch "$SECRETS_FILE"
    chown arkfile:arkfile "$SECRETS_FILE"
    chmod 640 "$SECRETS_FILE"
fi

# Check if ARKFILE_MASTER_KEY already exists in secrets.env
if grep -q "^ARKFILE_MASTER_KEY=" "$SECRETS_FILE"; then
    print_status "INFO" "Master Key already exists in secrets.env"
else
    print_status "INFO" "Generating new Master Key..."
    # Generate 32-byte hex-encoded key (64 hex characters)
    MASTER_KEY=$(openssl rand -hex 32)
    
    # Append to secrets.env
    echo "" >> "$SECRETS_FILE"
    echo "# Master Key for Envelope Encryption (generated by 03-setup-master-key.sh)" >> "$SECRETS_FILE"
    echo "ARKFILE_MASTER_KEY=$MASTER_KEY" >> "$SECRETS_FILE"
    
    print_status "SUCCESS" "Master Key generated and appended to $SECRETS_FILE"
fi

# Ensure correct permissions
chown arkfile:arkfile "$SECRETS_FILE"
chmod 640 "$SECRETS_FILE" # Read/write for owner, read for group, no access for others
